/*
 *  This file is part of varr-numerics, an experimental variable resolution
 *  primitive numerics library.
 *
 *  Copyright (C) 2019 Cardiff University
 *
 *  varr-numerics is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  varr-numerics is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with varr-numerics.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __VARR_SIXTH_ROOT_H__
#define __VARR_SIXTH_ROOT_H__

#include <stddef.h>

/*
 * An object that provides a VARR implementation of the real sixth-root 
 * function, pow(x, 1/6.).
 * 
 * This implementation provides a scalar real sixth-root function 
 * named 'sixthrootd'.
 */
typedef struct tagVARRSixthRootDEvaluator {
   void const * accelerator;
   
   /*
    * A VARR real sixth root function.  The first argument to this method
    * is the number, x, for which pow(x, 1/6.) is to be evaluated and returned.
    * x must be a finite strictly positive real number.
    */
   double (* sixthrootd) (double, void const * accelerator);
   
   /*
    * A vectorized VARR real sixth root function.  The meaning of arguments to 
    * this method are as follows:
    * 
    *    i..   'in' - a const array of doubles, being the values of x to 
    *          process;
    *    ii.   'out' - an array of doubles of (at least) the same length as 
    *          (i.), being the values of pow(x, 1./6) to assign;
    *    iii.  'length' - the length of the arrays (i.) and (ii.) above.
    *,   iv.   'accelerator' - the value of the above enclosed (void *) 
    *          accelerator.
    *
    * It is the responsibility of the caller to ensure that the arrays (i.) and 
    * (ii.) both have size (iii.).
    *
    * It is not necessary for the arrays (i.) or (ii.) to have any specific
    * alignments.  If this library is compiled without AVX extensions enabled,
    * this method will delegate to the above scalar VARR implementation of 
    * the real sixth root function.
    */
   void (* sixthrootd_array) (
      double const * in, double * out,
      size_t length, 
      void const * accelerator
      );
   
   int (* disallocate) (struct tagVARRSixthRootDEvaluator *);
} VARRSixthRootDEvaluator;

/*
 * Returns an object that provides a VARR implementation of the real 
 * sixth root function.   See documentation for the type VARRSixthRootDEvaluator
 * for further information.
 *
 * This implementation uses linear interpolation techniques combined with 
 * sampling and a modified De-Bruijn-like method to compute the real 
 * sixth root.
 * 
 * This function allocates a sampling grid of real sixth root values.
 * The size of this sampling grid is indicated by the argument 
 * 'number_of_samples', which must be nonzero.  The amount of memory allocated 
 * by this function is approximately proportional to the number of sampling 
 * points requested.  The numerical accuracy of the sixth root function 
 * that is generated by this method generally increases with the number of 
 * sampling points requested.
 *
 * When evaluating pow(x, 1/6.) (VARRSixthRootDEvaluator.sixthrootd(x)) using 
 * this method, all arguments x must be finite real numbers confined to the 
 * range 10**-18 < x < 10**+18.
 */
VARRSixthRootDEvaluator
linear_sampling_normalizing_sixth_rootd(size_t number_of_samples);

VARRSixthRootDEvaluator
sublinear_sampling_normalizing_sixth_rootd(size_t number_of_samples);

#endif /* __VARR_SIXTH_ROOT_H__ */
